#cloud-config
write_files:
  # Create empty file so it will always exist when mounting a volume to container.
  # When source file or directory is missing, docker will create a root-owned directory with same path and then
  # mount it inside container.
  - path: /etc/secret_file
    permissions: '0644'
    owner: root
    content: ''

  # Script that will take care of fetching the secret from secret manager, using VM service account access token
  - path: /etc/scripts/fetch-secret.sh
    permissions: '0755'
    owner: root
    content: |
      #!/bin/bash

      # this script:
      #   1. generates access token using google metadata server
      #   2. fetches the secret version contents
      #   3. decodes it and writes it to the /etc/secret_file

      set -e

      secret_version_id="projects/515460920183/secrets/EF2BotEnvFile/versions/2"

      access_token=$(
        curl http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token \
         -H 'Metadata-Flavor: Google' \
        | cut -d'"' -f 4
      )

      curl "https://secretmanager.googleapis.com/v1/$secret_version_id:access?fields=payload.data&prettyPrint=false" \
        -H "Authorization: Bearer $access_token" \
        -H 'Accept: application/json' | cut -d '"' -f 6 | base64 -d > /etc/secret_file
  - path: /etc/systemd/system/ef2-discord-bot.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=EF2 Discord Bot
      After=docker.service
      Requires=docker.service

      [Service]
      Environment="HOME=/home/ef2discordbot"

      # Ensure the old container is removed before attempting to run a new one
      ExecStartPre=/usr/bin/docker rm -f ef2-discord-bot

      # Authenticate docker using docker-credential-gcr
      # This uses the VM's service account identity automatically
      ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries us-west1-docker.pkg.dev

      # Now pull and run as before
      ExecStartPre=/usr/bin/docker pull us-west1-docker.pkg.dev/ef2-discord-bot/ef2-discord-bot/ef2-discord-bot:latest
      ExecStart=/usr/bin/docker run --name ef2-discord-bot \
        --log-driver=gcplogs \
        --env-file /etc/secret_file \
        -e DONATION_URL=https://paypal.me/MesaStephen \
        -e BOT_STATUS="Tracking EF2 SR progress" \
        -e COOLDOWN_SECONDS=3 \
        -e DB_SSL=true \
        us-west1-docker.pkg.dev/ef2-discord-bot/ef2-discord-bot/ef2-discord-bot:latest
      ExecStop=/usr/bin/docker stop ef2-discord-bot
      StandardOutput=journal
      StandardError=journal
      Restart=always

runcmd:
  - /etc/scripts/fetch-secret.sh
  - systemctl daemon-reload
  - systemctl enable --now ef2-discord-bot.service