name: Deploy Bot Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # Required to compile linux/arm64 on standard GitHub runners
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Required to use the 'docker buildx' command
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          project_id: 'ef2-discord-bot'
          workload_identity_provider: 'projects/515460920183/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-publisher@ef2-discord-bot.iam.gserviceaccount.com'

      - name: Build and Push Docker Image
        # Tags the image with BOTH the specific release tag (e.g., v1.1.0) and 'latest'
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t us-west1-docker.pkg.dev/ef2-discord-bot/ef2-discord-bot/ef2-discord-bot:${{ github.ref_name }} \
            -t us-west1-docker.pkg.dev/ef2-discord-bot/ef2-discord-bot/ef2-discord-bot:latest \
            --push .
